### ISSUE TITLE
v2: SplitInfo has no field named filepathTemplate and DatasetInfo has no field named releaseNotes

### ISSUE THREAD

**Issue by TheExGenesis** [google-research/FLAN#18]
Many datasets are throwing these 2 errors in particular. (over 200 tasks in Flan alone) I'll give 2 examples:

`seqio.get_mixture_or_task("ag_news_subset_template_0to10_x_shot").get_dataset(sequence_length={"inputs": 512, "targets": 512})
`
Error:
```
Failed to parse splits field: Message type "tensorflow_datasets.SplitInfo" has no field named "filepathTemplate".
Available Fields(except extensions): ['name', 'numShards', 'shardLengths', 'numBytes', 'statistics'].
```

---

`seqio.get_mixture_or_task("cnn_dailymail_template_0to10_no_opt_x_shot").get_dataset(sequence_length={"inputs": 512, "targets": 512})`
Error:
```
Message type "tensorflow_datasets.DatasetInfo" has no field named "releaseNotes".
 Available Fields(except extensions): ['name', 'description', 'version', 'configName', 'configDescription', 'citation', 'sizeInBytes', 'downloadSize', 'location', 'downloadChecksums', 'schema', 'splits', 'supervisedKeys', 'redistributionInfo', 'moduleName', 'disableShuffling', 'fileFormat']
```

**Comment by TheExGenesis** [comment]
I think these problems are solved by updating to the most recent version of tfds-nightly, the default version I got from pip wasn't updated.

**Comment by shayne-longpre** [comment]
@TheExGenesis Could you confirm this specific issue was fixed? (If so we will close this issue.)
