### ISSUE TITLE
Data distribution in language

### ISSUE THREAD

**Issue by siyuyuan** [google-research/FLAN#22]
Is there any specific data statistics in the distribution of datasets in language? I did not find the corresponding results in the paper.

**Comment by shayne-longpre** [comment]
Figure 18 in the Scaling Flan paper (https://arxiv.org/pdf/2210.11416.pdf) shows the frequency of languages across tasks. This is calculated from the "Languages" column in this dataset statistics file: https://github.com/google-research/FLAN/blob/main/flan/v2/flan_collection_info.csv

Thank you for your question!
