### ISSUE TITLE
Scale law In-consistency between flan-v1 and flan-v2

### ISSUE THREAD

**Issue by sxthunder** [google-research/FLAN#28]
LaMDA is instruct finetuned with flan-v1, the scale law shows only 68B and 137B model performance improves with instruct tuning.The reason instructing tuning fills up small model capacity(for example like a 8B model trained on 63 tasks).
However the scale law in "scaling instruction-fintuned language models(Training with flan-v2)", all model with capacity arrange from 8B-540B have performance improvement with instruct tuning, even using 1836 tasks.
Can anybody explain this? is there a concrete conclusion between the model size and num of instruct tuning tasks?

**Comment by shayne-longpre** [comment]
@sxthunder are you referring to Figure 7 in the first Flan paper (https://arxiv.org/pdf/2109.01652.pdf)? 

Our latest results in both Scaling Flan (https://arxiv.org/pdf/2210.11416.pdf Figure 4 and Table 5) and the Flan Collection (https://arxiv.org/pdf/2301.13688.pdf, Figure 4) show models as small as 100M parameters *can* improve from instruction tuning, and increasing the number of tasks does improve "held-out" task performance.

While I don't know for sure, I suspect there are a number of differences in the experiments which could have impacted the difference in observed scaling laws. For instance, the type of base model (what it was pre-trained on), the quality/diversity of instruction tuning tasks, and how different the instruction tuning tasks are from the eval tasks might all effect results.
