### ISSUE TITLE
Does each sub-mixture instructed both with zero-shot and few-shot?

### ISSUE THREAD

**Issue by sxthunder** [google-research/FLAN#31]
We have four sub-mixture: muffin, t0-sf, cot, niv2. And a set of instruction settings: zsopt, zsnoopt, fsopt, fsnoopt. Are scaling flan use the all the combinations? 
If so, does few-shot setting leak data information for zero-shot setting on a same dataset?
If not, can you give us the exact instruction settings on each sub-mixture?

**Comment by shayne-longpre** [comment]
@sxthunder Yes, we use all combinations in our final model. I'll update the README soon to clarify this.

As mentioned in #19 there is data leakage between the few-shot exemplars and and other training examples over the course of training. I would note though that we trained all our models this way, and it doesn't seem to have had a negative impact as far as we can tell. It's possible that splitting off a few-shot exemplar set of data might improve results, but it would also reduce the few-shot exemplar diversity. Curious to hear the results if anyone does this experiment.

**Comment by sxthunder** [comment]
@shayne-longpre Hi，Thanks for your reply. I have read your latest paper: [The Flan Collection: Designing Data and Methods for Effective Instruction Tuning ](https://arxiv.org/abs/2301.13688), which explain many training details of Flan-2022. Now we know four key elements of instruction tuning: COT, Input Inversion, Mixture Balance and Few Shot templates.
After reading a series of instruction tuning papers(Flan, T0...), can we conclude the possible steps to reproduce chatgpt:
+ it is necessary to finetune a naive pre-training model by dataset-instruct-tuning(using open source dataset with instructions, like Flan and T0). To preliminary learning how to follow a instruction, and improves its zero-shot ability on unseen task.
+ using some hand-write instruction dataset(like SFT step of instruct-gpt), because instructions in step 1 has some difference in open-ended. Like people will directly ask chatgpt "how to learning deep learning" without the instruction "ask the following question"
+ finally using RLFH to align the model output to human.....
