### ISSUE TITLE
FLAN few-shot template structure

### ISSUE THREAD

**Issue by tresiwald** [google-research/FLAN#35]
Hi, 

I have a question about the representation of few-shot tasks as instructions to query flan models. 

Does the following format follows the structure of the training instructions?

Thanks a lot for your feedback.

```

Is the following text a valid evidence regarding the given topic?

Options:
-yes
-no

Evidence: At the outset of his government, President Banzer launched a policy of using special police-units to physically eradicate the illegal coca of the Chapare region.
Topic: We should legalize the growing of coca leaf
Label: yes

Evidence: The U.S. Supreme Court has held that the terms "partial-birth abortion" and "intact dilation and extraction" are basically synonymous [REF].
Topic: We should ban partial birth abortions
Label: no

Evidence: A say on pay - a non-binding vote of the general meeting to approve director pay packages, is practised in a growing number of countries.
Topic: We should limit executive compensation
Label:

```

**Comment by shayne-longpre** [comment]
@tresiwald Generally, we are formatting them with the instruction provided with each exemplar, but there's a lot of variation, as you can see from all the `FewShotPattern` defined in this file: https://github.com/google-research/FLAN/blob/main/flan/v2/templates.py#L2191-L2201.

You can see the few shot pattern for each exemplar passed in to the formatting code here: https://github.com/google-research/FLAN/blob/4d7a9f40a8e47b6319baed7a682571c014afb52a/flan/v2/tasks.py#L169-L170.
