### ISSUE TITLE
Issues when run enumerate(dataset) in run_example.py

### ISSUE THREAD

**Issue by jianguoz** [google-research/FLAN#38]
When we try to run the `enumerate(dataset)` code in https://github.com/google-research/FLAN/blob/main/flan/v2/run_example.py#L108. The code gets stuck and cannot go to the following steps while our CPU memories are still enough. 

The dataset which mixed Flan, T0, NIV2, etc., in https://github.com/google-research/FLAN/blob/main/flan/v2/run_example.py#L65 may be too large with your provided default mix ratios. We then change 
```
DEFAULT_MIXTURE_MAX_EXAMPLES = {
    'FLAN': 30000,
    'T0': 20000,
    'CoT': 100000,
    'NIv2': 5000,
    'Dialog': 200000,
}
```
to 10 times and 100 times smaller, they still cannot run.

Do you have any suggestions here? Thanks

**Comment by shayne-longpre** [comment]
@jianguoz Yes, it's possible the number of data sources in the full Flan2022 mixture causes seqio an extremely long processing time. I would suggest generating 1 epoch of each submixture separately (flan2021, t0, niv2, ...), saving/caching each of them, and then combine them with the appropriate mixture rates yourself at the end into `flan2022`.

Hopefully this solves your problem? I will add a note to the `run_example.py` file with this suggestion if it works easier for you.
