### ISSUE TITLE
tfds version issue

### ISSUE THREAD

**Issue by joocjun** [google-research/FLAN#41]
I was trying to load qrecc and wiki_dialog from the dialogue section to find that the current tfds version installed by requirements doesn't include them. Updating the version seemed to fix it. I haven't checked if this particular update causes any problems in other areas, but if it seems okay could you update the version of tfds in the requirements?

**Comment by shayne-longpre** [comment]
@joocjun Thank you for your suggestion! To clarify, were you using the `flan/requirements.txt` file, or `flan/v2/requirements.txt`? For v2 we only want to use the latter. Maybe I can add a note to the READEM
