### ISSUE TITLE
BBH causal judgment reasoning

### ISSUE THREAD

**Issue by i-am-neo** [google-research/FLAN#42]
(Pls direct me to the best place to ask if needed).

Would you mind sharing UL2 results broken down by tasks for Big-Bench Hard? Causal Judgment, Disambiguation QA, Formal Fallacies, Hyperbaton, and Logical Deduction (Five Objects) would be of interest, as those are published for Flan-T5 series.

Thanks.

**Comment by shayne-longpre** [comment]
@i-am-neo I would email Yi Tay or his UL2 co-authors directly. https://www.yitay.net/

**Comment by i-am-neo** [comment]
Thank you Shayne.

**Comment by i-am-neo** [comment]
Hi Shayne, I got a bounce from Yi Tay's email.  Is he still at G?

In any case, I'm delving into "reasoning" from smaller models.  

It appears some in the Flan-T5 series (XL, XXL) may already have reasoning capabilities, but are less "adept" (than Flan-UL2) in expressing the rationales (what I "chain-of-reasoning" v pure cot).

And I believe this may have to do with the format of the data they were trained (strategyqa_train.tsv).  I'd like to run it by you.

This is what I mean by rationale:

If I ask a model: 
> Explain why a pound sterling is not valuable.

the answer would be:
> Because a pound sterling is fiat money and fiat money is backed by government decree and has no intrinsic value, a pound sterling is not valuable.

As frame of reference, the current entry in strategyqa_train.tsv is:
> Is a pound sterling valuable?	no	A pound sterling is fiat money. Fiat money is backed by government decree and has no intrinsic value. One pound sterling is worth about 1.24 US dollars by May of 2020.


Questions for you:
To achieve what I want, would you recommend fine-tuning a base model with just the 2061 lines in strategyqa_train.tsv, modified?  Might more data necessary (suggestions)?

Happy to continue this via email if preferred.

Thank you.

**Comment by shayne-longpre** [comment]
@i-am-neo He just posted today he's left Google, but can be reached at: yitay.llm@gmail.com.

For your examples on rationales, are you saying you'd prefer a single-sentence and more fluent response than what strategyqa_train currently provides? Otherwise the answers seem fairly close. I do think additional finetuning would help to hone the style/answer format you want. Just the modified version of StrategyQA might be enough.

You can email me at slongpre@media.mit.edu if you prefer, I don't mind. :)

**Comment by i-am-neo** [comment]
@shayne-longpre thank you for your input!

> For your examples on rationales, are you saying you'd prefer a single-sentence and more fluent response than what strategyqa_train currently provides? 

Yes.

> Otherwise the answers seem fairly close. 

That was my first thought, too. :)


I'll email you.
