### ISSUE TITLE
How were the Held-In and Held-Out splits created?

### ISSUE THREAD

**Issue by AadSah** [google-research/FLAN#46]
Hi @shayne-longpre, can you please point me to the script which was used for creating the held-in and held-out splits?

**Comment by shayne-longpre** [comment]
@AadSah The evaluation scripts are unfortunately not a part of the approved release. But those should be easy to replicate. "Held-Out" Tasks are [MMLU](https://github.com/hendrycks/test) or [BBH](https://github.com/suzgunmirac/BIG-Bench-Hard). "Held-In" evaluation tasks, as described in the Flan Collection paper, are simply the validation sets for those 8 datasets.
