### ISSUE TITLE
ERROR:absl:Failed to load task 'tfds_natural_instructions_template_0to10_zero_shot' as part of mixture 'palmflan_niv2_zs_opt'

### ISSUE THREAD

**Issue by AadSah** [google-research/FLAN#49]
Hi @shayne-longpre, thanks for answering the queries actively. I am using @SirNeural's script from https://huggingface.co/datasets/SirNeural/flan_v2 to create the dataset, but I am repeatedly facing this error:
```
ERROR:absl:Failed to load task 'tfds_natural_instructions_template_0to10_zero_shot' as part of mixture 'palmflan_niv2_zs_opt'
```

I have also checked out the issue which you have raised in the tensorflow repo here: https://github.com/tensorflow/datasets/issues/4804

I am wondering if you were able to find a fix to this?

Thanks!

**Comment by ari9dam** [comment]
I tried the script given in this repo. Niv2 works for me. Use python 3.8 while creating your env. I had to create a fresh env. However I'm facing issue with Apache Beam and dll.

**Comment by AadSah** [comment]
Nope, I am still facing the issue. Also, I am having this issue as well: https://github.com/google-research/FLAN/issues/37#issuecomment-1480018637

Any help on the latter part?
