### ISSUE TITLE
Questions about the training data sourced from Natural-instructions V2

### ISSUE THREAD

**Issue by adityarawal** [google-research/FLAN#5]
Question: Can you share the exact list of 1836 tasks used for training?

For example, I found a list of Super-natural-instructions tasks in your code-based but this includes less than 1000 tasks (including the held-out MMLU tasks): https://github.com/google-research/FLAN/blob/main/flan/v2/constants_niv2.py

**Comment by shayne-longpre** [comment]
Hi @adityarawal,

I've added this full list of the tasks/datasets used in the Flan Collection repo here: https://github.com/google-research/FLAN/blob/main/flan/v2/flan_collection_info.csv

Looking at the NIv2 constants file, it has 1654 keys, they're just sorted alphabetically, not by task number.

**Comment by shayne-longpre** [comment]
@adityarawal does this answer your question? Will close this issue if so.

**Comment by lehougoogle** [comment]
Closing this issue for now. Plz re-open if needed.
