### ISSUE TITLE
How to include metadata from flan_collection_info.csv in each data entry?

### ISSUE THREAD

**Issue by AadSah** [google-research/FLAN#62]
Hi @shayne-longpre 

I am trying to prepare the dataset with all the metadata mentioned in https://github.com/google-research/FLAN/blob/main/flan/v2/flan_collection_info.csv included. Do you know any quick workarounds which can help me do that?

Thanks!

**Comment by AadSah** [comment]
I am able to get the "source" and "dataset" metadata using the passthrough_features argument, but I am not sure how to include the "specific task category", "generic task category", and "languages" entries.

**Comment by shayne-longpre** [comment]
@AadSah You should be able to join the `_task_name` from `passthrough_features` to [flan_collection_info.csv](https://github.com/google-research/FLAN/blob/main/flan/v2/flan_collection_info.csv).

For "NIv2" tasks the `_task_name` should match the `"specific task category"`, and for the rest, the `_task_name` should match the `"dataset"`
