### ISSUE TITLE
Request for Training Code for Reproducibility and Research Purposes

### ISSUE THREAD

**Issue by Serena-LiuWx** [google-research/FLAN#63]
Hi @shayne-longpre ,

I am a graduate student working on LLMs and I am writing to request access to the training code associated with your paper, FLAN 2021, to reproduce your results and conduct further research.

I am greatly inspired by your work in FLAN 2021, especially the "number of instruction tuning clusters" part in ablation studies. Your findings have significant implications for my research, and I am eager to replicate your results and build upon your work, particularly to explore the connections between the type of training data and the performance of the model. Thank you so much for sharing the code to generate instruction tuning dataset, it would be really helpful if I could get the code to instruction tune the base model.

I understand that sharing the training code and data may require effort on your part, and I am committed to citing your work appropriately and complying with any terms or conditions associated with the use of the code and data. Your generosity in providing access to the training code and data would greatly contribute to the advancement of the field and foster a collaborative and open research environment.

Thank you for considering my request. I am looking forward to your positive response.

**Comment by shayne-longpre** [comment]
Hi @Serena-LiuWx thank you for your kind words and interest! Unfortunately, it is not within my power to release all the experiment code, as much as I would have liked to. It was a huge push to get the (significant) approvals required just to re-create an external version of the data processing pipeline you now see here. 

However, these experiments should not be hard to reproduce using public infrastructure like seqio and T5X. There are also a lot of repositories that have released instruction finetuning code on top of many models, including T5 (e.g. [T0](https://github.com/bigscience-workshop/t-zero)). You should be able to swap out the training data and make it work.

Hopefully this helps, and best of luck!

**Comment by Serena-LiuWx** [comment]
Thanks a lot for your advice!

**Comment by StephennFernandes** [comment]
is the training code out yet ?
