### ISSUE TITLE
T0 FS OPT - unable to process.

### ISSUE THREAD

**Issue by AadSah** [google-research/FLAN#65]
Hi @shayne-longpre, I have been using @SirNeural's script [here](https://huggingface.co/datasets/SirNeural/flan_v2) to generate the data. I have been able to generate all the files, except t0_fs_opt data. Every time I run the script, the process gets killed (with a prompt "Killed", and no error message) after some time. Also, the same data is unavailable in the data processed by @SirNeural in the huggingface repo. Did you face such issues earlier? Any help? :)

Thanks!

**Comment by shayne-longpre** [comment]
@AadSah Hmmm I'm not sure why that would be, other than it is the biggest submixture and longest to generate. One way to make it work is to process 1/4 of the datasets at a time. For instance, you could manually subset [this list](https://github.com/google-research/FLAN/blob/main/flan/v2/task_configs.py#L160) (once for each quarter), generate each quarter of the submixture, then combine them manually at the end.
