### ISSUE TITLE
Too many threads created

### ISSUE THREAD

**Issue by kiriharulxh** [google-research/FLAN#70]
Hi, thanks for the excellent work! I was trying to train a flan-t5-small model using the t5x code on gpu. But it turned out that the iteration of the mixture dataset for creating the first batch somehow created nearly 30000 threads and the program broke down, output exactly the same error as [the problem mentioned here](https://github.com/google-research/meta-dataset/issues/84).  I wonder if there's any problem with the way I use the t5x code and I'll appreciate it so much if there's any advice.

**Comment by xuanqing94** [comment]
hello @kiriharulxh , did you eventually solve this issue, if so, how?
