### ISSUE TITLE
Decoding parameters used in evaluation (Flan Collection)

### ISSUE THREAD

**Issue by ioana-blue** [google-research/FLAN#8]
First off, thank you for open-sourcing the collection of templates and data, etc. it can enable a lot more research! 

Could you please share the parameters that were used in decoding and any other details around decoding that could be useful in playing with Flan-T5? @shayne-longpre Thank you!

**Comment by lehougoogle** [comment]
Hi ioana-blue,

There's no critical decoding parameters as far as I can remember. You can use greedy decoding (temperature=0.0). And it's pretty obvious to set dropout=0.0

Let us know if you want to know the value of a specific parameter.

Thx

**Comment by ioana-blue** [comment]
@lehougoogle Thanks for the prompt reply! It would be nice to add this detail to the model card in the paper (I couldn't see this, it may be already in there).
