### ISSUE TITLE
QReCC processing does not match TFDS features

### ISSUE THREAD

**Issue by zphang** [google-research/FLAN#9]
The QReCC preprocessing code expects a `history_with_truth_answer` key:

https://github.com/google-research/FLAN/blob/36a9304a48793eaeb67c0407a1b751141ffbb29b/flan/v2/preprocessors.py#L1305

However, this key does not appear to be in the TFDS features: 

https://github.com/tensorflow/datasets/blob/e7649b4373c32d81946f40647a7a62ad475fb647/tensorflow_datasets/text/qrecc/qrecc.py#L53-L71

From a quick check, it does not appear in the original dataset files either.

**Comment by shayne-longpre** [comment]
Yep -- I realize the pre-processing code wasn't properly overwritten for the TFDS version. Looking into a solution but for now I'd say just comment it out.

**Comment by shayne-longpre** [comment]
This should be fixed with the recent PR by the way.

**Comment by zphang** [comment]
Thanks!
